stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules
    - dist

install-job:
  stage: install
  only:
    - main
  script:
    - yarn
    - echo "install success"

build-job:
  stage: build
  only:
    - main
  script:
    - sudo cp -r ./ /projects/server/blog
    - sudo cd /projects/server/blog
    - echo "build success"

deploy-job:
  stage: deploy
  only:
    - main
  before_script:
  script:
    - pm2 start --name server npm -- run start:test
  after_script:
    - echo "deploy success"