name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Compose
        uses: docker/compose-cli-action@v0.6.0
        with:
          compose-file: docker-compose.yml

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: my-nestjs-app:latest

      - name: Deploy with Docker Compose
        run: docker-compose up -d